// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3T3MVyVyzFBcXNjpXuGVr0sVFEGGIUAQ',
    appId: '1:881647430504:web:f1975ac50e7648d1f0c4dd',
    messagingSenderId: '881647430504',
    projectId: 'currencyconverter-61278',
    authDomain: 'currencyconverter-61278.firebaseapp.com',
    storageBucket: 'currencyconverter-61278.firebasestorage.app',
    measurementId: 'G-FVS5M9J5JP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlW7_VK4eNE-KtGIQ21IuZ1IwwNr23RFU',
    appId: '1:881647430504:android:79e403e08793b37ff0c4dd',
    messagingSenderId: '881647430504',
    projectId: 'currencyconverter-61278',
    storageBucket: 'currencyconverter-61278.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0rH7G4y6PU8miSLXlTh1oVUTuP4tBtsw',
    appId: '1:881647430504:ios:302c931d01056702f0c4dd',
    messagingSenderId: '881647430504',
    projectId: 'currencyconverter-61278',
    storageBucket: 'currencyconverter-61278.firebasestorage.app',
    iosBundleId: 'com.example.bookshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0rH7G4y6PU8miSLXlTh1oVUTuP4tBtsw',
    appId: '1:881647430504:ios:302c931d01056702f0c4dd',
    messagingSenderId: '881647430504',
    projectId: 'currencyconverter-61278',
    storageBucket: 'currencyconverter-61278.firebasestorage.app',
    iosBundleId: 'com.example.bookshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3T3MVyVyzFBcXNjpXuGVr0sVFEGGIUAQ',
    appId: '1:881647430504:web:33c6f8fd530b1f8cf0c4dd',
    messagingSenderId: '881647430504',
    projectId: 'currencyconverter-61278',
    authDomain: 'currencyconverter-61278.firebaseapp.com',
    storageBucket: 'currencyconverter-61278.firebasestorage.app',
    measurementId: 'G-CTNH7T15QJ',
  );
}
